### ISSUE TITLE
原来是这里发布，好吧，希望考虑下从天猫直接登陆的情况

### ISSUE THREAD

**Issue by linhcpg** [4thleaf/CSS_For_TaobaoLoginPage#1]
我在gf那边反馈过：
考虑一下，从天猫那边直接登陆的情况
https://greasyfork.org/zh-CN/forum/discussion/13029/%E8%80%83%E8%99%91%E4%B8%80%E4%B8%8B-%E4%BB%8E%E5%A4%A9%E7%8C%AB%E9%82%A3%E8%BE%B9%E7%9B%B4%E6%8E%A5%E7%99%BB%E9%99%86%E7%9A%84%E6%83%85%E5%86%B5?new=1

**Comment by wu67** [comment]
感谢反馈，稍微改了一下
- 天猫那边能默认用密码登录了；
- 要同时显示二维码，得装上另一个天猫登录样式；
- 另外二维码确实又能自己加载了，那个脚本已移除
